+incdir+../rtl/include
../rtl/cores/khoree/core/bpu.v
../rtl/cores/khoree/core/ctrl.v
../rtl/cores/khoree/core/ex.v
../rtl/cores/khoree/core/id.v
../rtl/cores/khoree/core/id_ex.v
../rtl/cores/khoree/core/if_id.v
../rtl/cores/khoree/core/pc_reg.v
../rtl/cores/khoree/core/pre_id.v
../rtl/cores/khoree/core/rib.v
../rtl/cores/khoree/core/tinyriscv.v
../rtl/cores/khoree/perips/i2c.v
../rtl/cores/khoree/perips/uart.v
../rtl/cores/khoree/soc/tinyriscv_soc_top.v
../rtl/cores/pjy/core/ctrl.v
../rtl/cores/pjy/core/ex.v
../rtl/cores/pjy/core/id.v
../rtl/cores/pjy/core/id_ex.v
../rtl/cores/pjy/core/if_id.v
../rtl/cores/pjy/core/pc_reg.v
../rtl/cores/pjy/core/rib.v
../rtl/cores/pjy/core/tinyriscv.v
../rtl/cores/pjy/perips/i2c.v
../rtl/cores/pjy/perips/if_uart_sender.v
../rtl/cores/pjy/perips/sid_uart_sender.v
../rtl/cores/pjy/perips/uart.v
../rtl/cores/pjy/soc/tinyriscv_soc_top.v
../rtl/cores/pjy/utils/gen_dff.v
../rtl/cores/yc/core/ctrl.v
../rtl/cores/yc/core/ex.v
../rtl/cores/yc/core/id.v
../rtl/cores/yc/core/id_ex.v
../rtl/cores/yc/core/if_id.v
../rtl/cores/yc/core/pc_reg.v
../rtl/cores/yc/core/rib.v
../rtl/cores/yc/core/tinyriscv.v
../rtl/cores/yc/perips/bridge_core.v
../rtl/cores/yc/perips/i2c.v
../rtl/cores/yc/perips/uart.v
../rtl/cores/yc/soc/tinyriscv_soc_top.v
../rtl/cores/yc/utils/gen_dff.v
../rtl/cores/yx/core/core_fsm.v
../rtl/cores/yx/core/ctrl.v
../rtl/cores/yx/core/ex.v
../rtl/cores/yx/core/id.v
../rtl/cores/yx/core/id_ex.v
../rtl/cores/yx/core/if_id.v
../rtl/cores/yx/core/pc_reg.v
../rtl/cores/yx/core/rib.v
../rtl/cores/yx/core/rt.v
../rtl/cores/yx/core/sid.v
../rtl/cores/yx/core/tinyriscv.v
../rtl/cores/yx/perips/i2c.v
../rtl/cores/yx/perips/uart.v
../rtl/cores/yx/soc/tinyriscv_soc_top.v
../rtl/cores/yx/utils/gen_dff.v
../rtl/shared/yc_pwm.v
../rtl/shared/yc_regs.v
../rtl/shared/yc_uart_debug.v
../rtl/tinyriscv_4core_top.v
